// Google places autocomplete component 

//import PlacesAutocomplete from "react-places-autocomplete";

<PlacesAutocomplete onChange={setAddress} value={address}>
{/* needs a render prop func as a child */}
{({
  getInputProps,
  suggestions,
  getSuggestionItemProps,
  loading,
}) => {
  return (
    <>
      <div className="form-control">
        <label htmlFor="address">Address</label>
        <input
          {...getInputProps({
            placeholder: "Type your address",
          })}
          type="text"
          name="address"
        />

        {/* loading */}
        <div className="suggestions">
          {loading ? <div>...loading</div> : null}
          {/* rendering suggestions */}
          {suggestions.map((suggestion) => {
            const style = {
              backgroundColor: suggestion.active
                ? "#9a9b9b"
                : "#8b9090",
              padding: "5px",
              cursor: "pointer",
            };
            // props are generated by ...getSuggestionItemProps - where clickable prop among others comes from,  1st arg is sugg then we pass our props in
            return (
              <div
                {...getSuggestionItemProps(suggestion, {
                  style,
                })}
                key={Math.random()}
              >
                {suggestion.description}
              </div>
            );
          })}
        </div>
      </div>
    </>
  );
}}
</PlacesAutocomplete> 